class Casa {
    constructor(lugar,informacion,img,id,valor)
    {
        this.id = id;
        this.lugar = lugar;
        this.informacion = informacion;
        this.img = img;
        this.valor = valor;
    }
}
 
const Casas = [new Casa('California', 'Introducing an incredible opportunity to own a triplex at 13436 Beach Avenue, located in the highly desirable 90292 zip code. This property is situated just steps from the beautiful sandy shores of Marina Del Rey and offers a great investment opportunity.The triplex features three separate units. One of the units has been restored an is nicely appointed The outdoor area is perfect for enjoying the beautiful California weather. One unit is tenant occupied -Located just moments from the beach, this property is perfectly situated to enjoy all the outdoor activities that Marina Del Rey has to offer. Additionally, the location is close to nearby restaurants and other amenities, ensuring that residents have plenty of options for entertainment and dining. Dont miss out on this opportunity to own a triplex in desirable Marina Del Rey.',1,1,'100USD'),
new Casa('Oregon', 'Introducing an incredible opportunity to own a triplex at 13436 Beach Avenue, located in the highly desirable 90292 zip code. This property is situated just steps from the beautiful sandy shores of Marina Del Rey and offers a great investment opportunity.The triplex features three separate units. One of the units has been restored an is nicely appointed The outdoor area is perfect for enjoying the beautiful California weather. One unit is tenant occupied -Located just moments from the beach, this property is perfectly situated to enjoy all the outdoor activities that Marina Del Rey has to offer. Additionally, the location is close to nearby restaurants and other amenities, ensuring that residents have plenty of options for entertainment and dining. Dont miss out on this opportunity to own a triplex in desirable Marina Del Rey.',2,2,'130USD'),
new Casa('Madrid', 'Introducing an incredible opportunity to own a triplex at 13436 Beach Avenue, located in the highly desirable 90292 zip code. This property is situated just steps from the beautiful sandy shores of Marina Del Rey and offers a great investment opportunity.The triplex features three separate units. One of the units has been restored an is nicely appointed The outdoor area is perfect for enjoying the beautiful California weather. One unit is tenant occupied -Located just moments from the beach, this property is perfectly situated to enjoy all the outdoor activities that Marina Del Rey has to offer. Additionally, the location is close to nearby restaurants and other amenities, ensuring that residents have plenty of options for entertainment and dining. Dont miss out on this opportunity to own a triplex in desirable Marina Del Rey.',3,3,'120USD'),
new Casa('Andorra', 'Introducing an incredible opportunity to own a triplex at 13436 Beach Avenue, located in the highly desirable 90292 zip code. This property is situated just steps from the beautiful sandy shores of Marina Del Rey and offers a great investment opportunity.The triplex features three separate units. One of the units has been restored an is nicely appointed The outdoor area is perfect for enjoying the beautiful California weather. One unit is tenant occupied -Located just moments from the beach, this property is perfectly situated to enjoy all the outdoor activities that Marina Del Rey has to offer. Additionally, the location is close to nearby restaurants and other amenities, ensuring that residents have plenty of options for entertainment and dining. Dont miss out on this opportunity to own a triplex in desirable Marina Del Rey.',4,4,'123USD'),
new Casa('Grecia', 'Introducing an incredible opportunity to own a triplex at 13436 Beach Avenue, located in the highly desirable 90292 zip code. This property is situated just steps from the beautiful sandy shores of Marina Del Rey and offers a great investment opportunity.The triplex features three separate units. One of the units has been restored an is nicely appointed The outdoor area is perfect for enjoying the beautiful California weather. One unit is tenant occupied -Located just moments from the beach, this property is perfectly situated to enjoy all the outdoor activities that Marina Del Rey has to offer. Additionally, the location is close to nearby restaurants and other amenities, ensuring that residents have plenty of options for entertainment and dining. Dont miss out on this opportunity to own a triplex in desirable Marina Del Rey.',5,5,'90USD'),
new Casa('Mykonos', 'Introducing an incredible opportunity to own a triplex at 13436 Beach Avenue, located in the highly desirable 90292 zip code. This property is situated just steps from the beautiful sandy shores of Marina Del Rey and offers a great investment opportunity.The triplex features three separate units. One of the units has been restored an is nicely appointed The outdoor area is perfect for enjoying the beautiful California weather. One unit is tenant occupied -Located just moments from the beach, this property is perfectly situated to enjoy all the outdoor activities that Marina Del Rey has to offer. Additionally, the location is close to nearby restaurants and other amenities, ensuring that residents have plenty of options for entertainment and dining. Dont miss out on this opportunity to own a triplex in desirable Marina Del Rey.',6,6,'200USD')]





export default Casas;